### ISSUE TITLE
Clarification for singular/plural of slug and similar terms needed

### ISSUE THREAD

**Issue by ToBe998** [bolt/docs#362]
Working with bolt a few years now and i am constantly tripping over this issue:

In bolt contenttypes, we have **name**, **singular_name**, **slug**, **singular_slug**, **table_name** and maybe even more. Some of these values are auto generated from others (sometimes changing from singular to plural or other way round), some methods support both quantities and some don't.
The documentation only has one short sentence in the contenttypes section for slug and singular_slug, telling us that they can be auto-generated and affect stuff.

Confusion with quantity here leads to problems with urls having wrong quantity, fetch functions returning empty results, labels confusing editors, broken relations, extensions not working correctly  and troubles with manual database changes (ex: in migration scripts).

**So the questions needing clarification are**:

1) Which of the 5 fields should be specified in what quantity (singular or plural)
2) which of these fields can be auto-generated and from what other field
3) Which functions (especially `setcontent`) support both quantities
4) Which field and in what quantity is used in what internal logic (especially in the database)
5) And a small side question: The key of a contenttype inside the contenttypes.yml doesnt seem to be used for anything right?

I would gladly help with writing additions to the docs here, sadly i still cant fully answer these questions.

**Comment by SahAssar** [comment]
1. You need to specify either `slug` or `name` and either `singular_slug` or `singular_name`. If the slug versions are not specified they will be generated by slugifying the name. If the name versions are not specified they will be generated by title-casing the slugs. `table_name` will be the database prefix (default: `bolt_`) concatenated with the `slug`.
2. See above.
3. setcontent accepts both the `singular_slug` and the `slug`. To the best of my knowledge those are used interchangeably, but the docs suggest otherwise.
4. Bolt uses generally uses `slug` internally IIRC. For database logic it uses `table_name`, see 1 for how it is generated.
5. Correct. So this is a valid contenttype:
```
-
  slug: pages
  singular_slug: page
  fields:
    title:
      type: text
```

**Comment by SahAssar** [comment]
Hmm, Seems like even though not having a `name` and `singular_name` will "work" it will not work well... Some places in the backend will just be blank where the name should be.
