### ISSUE TITLE
Doc : updating with "composer install"

### ISSUE THREAD

**Issue by mouts** [bolt/docs#654]
The documentation suggested to use the "composer update" command to update the project from command line (or from a git clone). Why don't use the composer.lock file and "composer install" command ?

**Comment by bobdenotter** [comment]
Because `composer update` is for updating, and `composer install` is for installing what is locked down in the lock file. :-)

**Comment by mouts** [comment]
wrong way ;)

`composer update` is used for development and  `composer install` for production.

`composer install` is used to install **and update** dependencies using composer.lock. So dependencies are exactly the same for the production version and the released version. This is the expected behavior for production.

more information here : ["composer update" vs "composer install"](https://adamcod.es/2013/03/07/composer-install-vs-composer-update.html)

**Comment by bobdenotter** [comment]
I think you and I are saying almost the same thing. 

> composer install is used to install and update dependencies using composer.lock. 

Well, It installs whatever is in the lock file, and that _might_ be newer versions than previously installed. But it won't update to newer versions than locked down.

**Comment by mouts** [comment]
Hum, I see. So the only way to get the composer.lock is to download the distribution file of the latest version ? What's the recommended way to upgrade a bolt project ?

Thanks for the answers ! ;)

**Comment by bobdenotter** [comment]
The "recommended" way is either by downloading a new `.tgz` or `.zip` build, or by simply running `composer update`. We strive to keep our stuff up to date, so you are not likely to break your install. 

(But, as you said: on DEV you run `composer update`, check your fresh composer.lock into your git, and on PROD you run `composer install` only!)

**Comment by mouts** [comment]
OK, thanks for your answers and for the bolt project :)

**Comment by GawainLynch** [comment]
In an attempt to put this on the straight an narrow … :angry: 

**Neither** `composer update` or `composer install` are for development or production! Seriously, read some docs!

As @bobdenotter mentions, the lock file is created/updated by serveral composer commands to set the **projects** package versions in a way that *all* developers can safely work on the same versions. If I am working with a developer and they run `composer update` on a locked install … They are going to have a bad day when I get to their desk.

Conversely, in production you should be using deploy scripts … so never running it anyway, we all do s, let's just pretend that bit of "naughtiness" doesn't happen … 

Simplistically:
  * `composer update` should only be run by the team lead, by agreement in the dev team, or to update a *single* package (usually a data package, rather than a functional one)
  * `composer install` every … other … time …
